# Generated by Django 2.1.7 on 2019-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=70)),
                ('e_con_no', models.CharField(max_length=10)),
                ('e_mail', models.CharField(max_length=50)),
                ('e_pass', models.CharField(max_length=20)),
                ('e_id_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Labours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=70)),
                ('l_con_no', models.CharField(max_length=10)),
                ('l_pass', models.CharField(max_length=20)),
                ('l_id_no', models.CharField(max_length=50)),
                ('l_addr', models.CharField(max_length=100)),
                ('pres', models.IntegerField(default=0)),
            ],
        ),
    ]
