# Generated by Django 2.1.7 on 2019-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_con_no', models.CharField(max_length=10)),
                ('l_con_no', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
